version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/elixir:1.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "mix.lock" }}
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix test
      - save_cache:
          key: dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - restore_cache:
          keys:
            - dialyzer-cache-{{ checksum "mix.lock" }}
      - run: MIX_ENV=test mix dialyzer --plt
      - save_cache:
          key: dialyzer-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix
      - run: MIX_ENV=test mix dialyzer --halt-exit-status
      - run: MIX_ENV=test mix credo
      - run: MIX_ENV=test mix inch.report
